services:
    #sonata.admin.tag:
    #    class: Tvs\AdminBundle\Admin\TagAdmin
    #    tags:
    #        - { name: sonata.admin, manager_type: orm, group: posts, label: "Tag" }
    #    arguments:
    #        - ~
    #        - Tvs\AdminBundle\Entity\Course
    #        - 'SonataAdminBundle:CRUD'
    #    calls:
    #        - [ setTranslationDomain, [TvsAdminBundle]]