parameters:
#    tvs_admin.example.class: Tvs\AdminBundle\Example

services:
#    tvs_admin.example:
#        class: %tvs_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
