parameters:
#    inthe_dev.example.class: Inthe\DevBundle\Example

services:
#    inthe_dev.example:
#        class: %inthe_dev.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
